# Generated by Django 2.2.7 on 2020-04-01 14:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='taskitem',
            options={'ordering': ['task_due_date']},
        ),
        migrations.AlterModelOptions(
            name='tasklist',
            options={'ordering': ['task_list_name']},
        ),
        migrations.AlterField(
            model_name='taskitem',
            name='task_created_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 1, 9, 23, 42, 746625)),
        ),
        migrations.AlterField(
            model_name='taskitem',
            name='task_due_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 1, 9, 23, 42, 746647)),
        ),
    ]
