# Generated by Django 2.2.7 on 2020-04-08 01:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0016_auto_20200405_1701'),
        ('models', '0020_auto_20200407_1048'),
    ]

    operations = [
    ]
