# Generated by Django 3.0.5 on 2020-04-08 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0028_auto_20200408_0516'),
        ('models', '0039_auto_20200408_1038'),
        ('models', '0026_auto_20200408_1041'),
    ]

    operations = [
    ]
