# Generated by Django 3.0.5 on 2020-04-13 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0055_auto_20200412_1932'),
        ('models', '0055_auto_20200412_1836'),
    ]

    operations = [
    ]
