language: python
python:
- '3.8'
install:
- pip install -r requirements-travis.txt
script:
- python manage.py test
deploy:
  provider: heroku
  api_key:
    secure: EBdSFdg96DOz+B2QzfH5xafjLlqGtM37/jM/jutDhIFDulmZMq3DnOs/25uW8oFL3peO7IoqBKZ7iXhk9MRum54mXWIozIg7ovmk2iPVzQuhAGoLlsQABUDBZ346UmGXynoSUEy+KNrax+JlmCSPLHiNOwX8UWtqzG+6xqDR81ZmrY2r6RPg2ixZvZn5AIZ37fjurl4hQdTzZzt8If5kngvgTJRA5f3LIL+z/iF6icOcs9H1wY1Pp0tshsPqnnb87JX16r58dlPZ/qZjLiO9YMtK8OVbuI/SDpmVT2MTxEcG5CM9gtpRDPbdXrPRxuh89fHXGvylBAAl253R4k+Q70+zR7xVorkIZ76m28gdtZXytOFx8Zr30aDNMkFK8Lv6LNOUpwXsSXoCJu+YmKA8CiEAzzK9ZsenkvIB/z1aVwvyHM1uqdp9VKU1Pipi2UFi+lZo3zetrLkX1z//yMsppvTLHAPBqnoPLH3cdAwfqPtVj41vawjIjVNnGIusM4mL+Jc2Sg9wmygZeTg30GtEtU3jIFl3oQUt0VmmyQKIIowhN1DMza+rw+GqeuB9/99Wcj1uI7fo7BaV8j+ZGKkB2IiaP3PRb21X2OABhJQdlzzcpuaVXldCiyB+1YfaOujWQVnNWO+mq4BtAIdVfk08ptQX5eFqGFkUNVdHkMXtqKQ=
  app: project-101-pdnj
  on:
    repo: uva-cs3240-s20/project-101-pdnj
