# Generated by Django 3.0.3 on 2020-03-02 08:37

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_auto_20200302_0245'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Course',
        ),
        migrations.DeleteModel(
            name='Event',
        ),
        migrations.DeleteModel(
            name='EventList',
        ),
        migrations.DeleteModel(
            name='Grade',
        ),
        migrations.DeleteModel(
            name='GradeCategory',
        ),
        migrations.DeleteModel(
            name='TaskListGroup',
        ),
        migrations.RemoveField(
            model_name='task',
            name='due_date',
        ),
        migrations.RemoveField(
            model_name='tasklist',
            name='tasklist_description',
        ),
        migrations.RemoveField(
            model_name='tasklist',
            name='tasklist_name',
        ),
        migrations.AddField(
            model_name='task',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 2, 8, 37, 30, 979562, tzinfo=utc), verbose_name='date due'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tasklist',
            name='list_name',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='task',
            name='task_name',
            field=models.CharField(max_length=200),
        ),
    ]
