# Generated by Django 3.0.3 on 2020-03-02 18:12

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_auto_20200302_0337'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(default='Event', max_length=100)),
                ('event_description', models.CharField(default='Event description', max_length=500)),
                ('date_time', models.DateTimeField(default=datetime.datetime(2020, 3, 2, 18, 12, 14, 782300, tzinfo=utc), verbose_name='event date and time')),
            ],
        ),
        migrations.CreateModel(
            name='EventList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventlist_name', models.CharField(max_length=100)),
                ('eventlist_description', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='TaskListGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tasklist_group_name', models.CharField(default='TaskList Group', max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='task',
            name='pub_date',
        ),
        migrations.RemoveField(
            model_name='tasklist',
            name='list_name',
        ),
        migrations.AddField(
            model_name='task',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 3, 18, 12, 14, 779065, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='tasklist',
            name='tasklist_description',
            field=models.CharField(default='A list of tasks.', max_length=500),
        ),
        migrations.AddField(
            model_name='tasklist',
            name='tasklist_name',
            field=models.CharField(default='Task List', max_length=100),
        ),
        migrations.AddField(
            model_name='tasklist',
            name='tasks',
            field=models.ManyToManyField(to='backend.Task'),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_description',
            field=models.CharField(default='Task description', max_length=500),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_name',
            field=models.CharField(default='Task', max_length=100),
        ),
        migrations.CreateModel(
            name='Subtask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(default='Task', max_length=100)),
                ('task_description', models.CharField(default='Task description', max_length=500)),
                ('due_date', models.DateTimeField(default=datetime.datetime(2020, 3, 3, 18, 12, 14, 779628, tzinfo=utc))),
                ('parent_task', models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to='backend.Task')),
            ],
        ),
        migrations.CreateModel(
            name='GradeCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=100)),
                ('parent_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Course')),
            ],
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade_name', models.CharField(default='Grade', max_length=100)),
                ('earned_points', models.IntegerField()),
                ('possible_points', models.IntegerField()),
                ('parent_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.GradeCategory')),
            ],
        ),
    ]
