# Generated by Django 3.0.3 on 2020-03-02 18:19

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_auto_20200302_1312'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='due_date',
        ),
        migrations.AddField(
            model_name='task',
            name='parent_task',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to='backend.Task'),
        ),
        migrations.AddField(
            model_name='task',
            name='task_due_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 3, 18, 19, 59, 4859, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='event',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 2, 18, 19, 59, 7427, tzinfo=utc), verbose_name='event date and time'),
        ),
        migrations.DeleteModel(
            name='Subtask',
        ),
    ]
