# Generated by Django 3.0.3 on 2020-03-02 18:34

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_auto_20200302_1334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_due_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 3, 18, 34, 45, 580339, tzinfo=utc)),
        ),
    ]
