# Generated by Django 3.0.3 on 2020-03-02 18:36

import backend.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_auto_20200302_1334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_due_date',
            field=models.DateTimeField(default=backend.models.tomorrow),
        ),
    ]
