# Generated by Django 3.0.3 on 2020-04-01 02:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0013_auto_20200331_1849'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Event',
        ),
        migrations.DeleteModel(
            name='EventList',
        ),
        migrations.RemoveField(
            model_name='grade',
            name='parent_category',
        ),
        migrations.RemoveField(
            model_name='gradecategory',
            name='parent_course',
        ),
        migrations.DeleteModel(
            name='TaskListGroup',
        ),
        migrations.AddField(
            model_name='tasklist',
            name='user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Course',
        ),
        migrations.DeleteModel(
            name='Grade',
        ),
        migrations.DeleteModel(
            name='GradeCategory',
        ),
    ]
